IF Object_Id('Categories') IS NULL 
BEGIN
  
CREATE TABLE Categories 
(
Id INT IDENTITY(1,1) NOT NULL,
[Name] VARCHAR(100) NOT NULL,

CONSTRAINT PK_Categories PRIMARY KEY CLUSTERED ([Id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]) ON [PRIMARY] 
END
GO